"""
Task service containing business logic.
"""

from datetime import datetime
from typing import Optional, List, Tuple, Dict
from uuid import UUID
from sqlalchemy.orm import Session
from sqlalchemy import and_, or_

from app.models.task import Task, Subtask, TaskStatus
from app.models.event import Event
from app.modules.tasks.schema import TaskCreate, TaskUpdate, TaskStatusUpdate, SubtaskCreate, SubtaskUpdate
from app.core.exceptions import NotFoundError, AuthorizationError


class TaskService:
    """Service for task-related operations."""

    @staticmethod
    def create_task(
        db: Session,
        event_id: str,
        user_id: str,
        task_data: TaskCreate,
        ai_generated: bool = False,
    ) -> Task:
        """
        Create a new task for an event.

        Args:
            db: Database session
            event_id: Event ID (string or UUID)
            user_id: User ID (for ownership verification)
            task_data: Task creation data
            ai_generated: Whether task was generated by AI

        Returns:
            Created Task object

        Raises:
            NotFoundError: If event not found
            AuthorizationError: If user doesn't own the event
        """
        # Verify event ownership
        if isinstance(event_id, str):
            event_id = UUID(event_id)

        event = db.query(Event).filter(
            Event.id == event_id,
            Event.deleted_at.is_(None)
        ).first()

        if not event:
            raise NotFoundError("Event", str(event_id))

        if event.user_id != user_id:
            raise AuthorizationError("You don't have permission to create tasks for this event")

        db_task = Task(
            event_id=event_id,
            title=task_data.title,
            description=task_data.description,
            priority=task_data.priority,
            category=task_data.category,
            due_date=task_data.due_date,
            assigned_to=task_data.assigned_to,
            ai_generated=ai_generated,
        )
        db.add(db_task)
        db.commit()
        db.refresh(db_task)
        return db_task

    @staticmethod
    def get_tasks(
        db: Session,
        event_id: str,
        user_id: str,
        skip: int = 0,
        limit: int = 10,
        status: Optional[str] = None,
        priority: Optional[str] = None,
        category: Optional[str] = None,
        search: Optional[str] = None,
    ) -> Tuple[int, List[Task]]:
        """
        Get tasks for an event with filtering.

        Args:
            db: Database session
            event_id: Event ID
            user_id: User ID (for ownership verification)
            skip: Number of records to skip
            limit: Number of records to return
            status: Filter by task status
            priority: Filter by task priority
            category: Filter by task category
            search: Search in title/description

        Returns:
            Tuple of (total_count, tasks_list)

        Raises:
            NotFoundError: If event not found
            AuthorizationError: If user doesn't own the event
        """
        # Verify event ownership
        if isinstance(event_id, str):
            event_id = UUID(event_id)

        event = db.query(Event).filter(
            Event.id == event_id,
            Event.deleted_at.is_(None)
        ).first()

        if not event:
            raise NotFoundError("Event", str(event_id))

        if event.user_id != user_id:
            raise AuthorizationError("You don't have permission to view tasks for this event")

        query = db.query(Task).filter(
            Task.event_id == event_id,
            Task.deleted_at.is_(None)
        )

        # Apply filters
        if status:
            query = query.filter(Task.status == status)
        if priority:
            query = query.filter(Task.priority == priority)
        if category:
            query = query.filter(Task.category == category)
        if search:
            search_term = f"%{search}%"
            query = query.filter(
                or_(
                    Task.title.ilike(search_term),
                    Task.description.ilike(search_term)
                )
            )

        total = query.count()
        tasks = query.order_by(Task.created_at.desc()).offset(skip).limit(limit).all()

        return total, tasks

    @staticmethod
    def get_tasks_grouped_by_status(
        db: Session,
        event_id: str,
        user_id: str,
        priority: Optional[str] = None,
        category: Optional[str] = None,
        search: Optional[str] = None,
    ) -> Dict[str, List[Task]]:
        """
        Get tasks grouped by status for Kanban board.

        Args:
            db: Database session
            event_id: Event ID
            user_id: User ID (for ownership verification)
            priority: Filter by priority
            category: Filter by category
            search: Search term

        Returns:
            Dictionary with status keys and task lists

        Raises:
            NotFoundError: If event not found
            AuthorizationError: If user doesn't own the event
        """
        # Verify event ownership
        if isinstance(event_id, str):
            event_id = UUID(event_id)

        event = db.query(Event).filter(
            Event.id == event_id,
            Event.deleted_at.is_(None)
        ).first()

        if not event:
            raise NotFoundError("Event", str(event_id))

        if event.user_id != user_id:
            raise AuthorizationError("You don't have permission to view tasks for this event")

        query = db.query(Task).filter(
            Task.event_id == event_id,
            Task.deleted_at.is_(None)
        )

        # Apply filters
        if priority:
            query = query.filter(Task.priority == priority)
        if category:
            query = query.filter(Task.category == category)
        if search:
            search_term = f"%{search}%"
            query = query.filter(
                or_(
                    Task.title.ilike(search_term),
                    Task.description.ilike(search_term)
                )
            )

        tasks = query.order_by(Task.created_at.desc()).all()

        # Group by status
        grouped = {
            "pending": [],
            "in_progress": [],
            "completed": [],
        }

        for task in tasks:
            status_key = task.status.value.lower().replace("_", "_")
            if task.status == TaskStatus.PENDING:
                grouped["pending"].append(task)
            elif task.status == TaskStatus.IN_PROGRESS:
                grouped["in_progress"].append(task)
            elif task.status == TaskStatus.COMPLETED:
                grouped["completed"].append(task)

        return grouped

    @staticmethod
    def get_task_by_id(
        db: Session,
        task_id: str,
        user_id: str,
    ) -> Task:
        """
        Get a task by ID with ownership verification through event.

        Args:
            db: Database session
            task_id: Task ID
            user_id: User ID (for ownership verification)

        Returns:
            Task object

        Raises:
            NotFoundError: If task not found
            AuthorizationError: If user doesn't own the event
        """
        if isinstance(task_id, str):
            task_id = UUID(task_id)

        task = db.query(Task).filter(
            Task.id == task_id,
            Task.deleted_at.is_(None)
        ).first()

        if not task:
            raise NotFoundError("Task", str(task_id))

        # Verify event ownership
        event = db.query(Event).filter(Event.id == task.event_id).first()
        if event.user_id != user_id:
            raise AuthorizationError("You don't have permission to access this task")

        return task

    @staticmethod
    def update_task(
        db: Session,
        task_id: str,
        user_id: str,
        task_data: TaskUpdate,
    ) -> Task:
        """
        Update a task.

        Args:
            db: Database session
            task_id: Task ID
            user_id: User ID (for ownership verification)
            task_data: Task update data

        Returns:
            Updated Task object

        Raises:
            NotFoundError: If task not found
            AuthorizationError: If user doesn't own the event
        """
        task = TaskService.get_task_by_id(db, task_id, user_id)

        # Update only provided fields
        update_data = task_data.model_dump(exclude_unset=True)
        for field, value in update_data.items():
            setattr(task, field, value)

        task.updated_at = datetime.utcnow()
        db.commit()
        db.refresh(task)
        return task

    @staticmethod
    def update_task_status(
        db: Session,
        task_id: str,
        user_id: str,
        status_data: TaskStatusUpdate,
    ) -> Task:
        """
        Update only task status.

        Args:
            db: Database session
            task_id: Task ID
            user_id: User ID (for ownership verification)
            status_data: New status

        Returns:
            Updated Task object

        Raises:
            NotFoundError: If task not found
            AuthorizationError: If user doesn't own the event
        """
        task = TaskService.get_task_by_id(db, task_id, user_id)
        task.status = status_data.status
        task.updated_at = datetime.utcnow()
        db.commit()
        db.refresh(task)
        return task

    @staticmethod
    def delete_task(
        db: Session,
        task_id: str,
        user_id: str,
    ) -> None:
        """
        Soft delete a task.

        Args:
            db: Database session
            task_id: Task ID
            user_id: User ID (for ownership verification)

        Raises:
            NotFoundError: If task not found
            AuthorizationError: If user doesn't own the event
        """
        task = TaskService.get_task_by_id(db, task_id, user_id)
        task.deleted_at = datetime.utcnow()
        db.commit()

    @staticmethod
    def create_subtask(
        db: Session,
        task_id: str,
        user_id: str,
        subtask_data: SubtaskCreate,
    ) -> Subtask:
        """
        Create a subtask for a task.

        Args:
            db: Database session
            task_id: Task ID
            user_id: User ID (for ownership verification)
            subtask_data: Subtask creation data

        Returns:
            Created Subtask object

        Raises:
            NotFoundError: If task not found
            AuthorizationError: If user doesn't own the event
        """
        # Verify task ownership through event
        task = TaskService.get_task_by_id(db, task_id, user_id)

        # Get next order number
        max_order = db.query(Subtask).filter(Subtask.task_id == task.id).count()

        db_subtask = Subtask(
            task_id=task.id,
            title=subtask_data.title,
            description=subtask_data.description,
            status=subtask_data.status or TaskStatus.PENDING,
            order=max_order,
        )
        db.add(db_subtask)
        db.commit()
        db.refresh(db_subtask)
        return db_subtask

    @staticmethod
    def get_subtask_by_id(
        db: Session,
        subtask_id: str,
        user_id: str,
    ) -> Subtask:
        """
        Get a subtask by ID with ownership verification.

        Args:
            db: Database session
            subtask_id: Subtask ID
            user_id: User ID (for ownership verification)

        Returns:
            Subtask object

        Raises:
            NotFoundError: If subtask not found
            AuthorizationError: If user doesn't own the event
        """
        if isinstance(subtask_id, str):
            subtask_id = UUID(subtask_id)

        subtask = db.query(Subtask).filter(Subtask.id == subtask_id).first()

        if not subtask:
            raise NotFoundError("Subtask", str(subtask_id))

        # Verify task ownership through event
        task = db.query(Task).filter(Task.id == subtask.task_id).first()
        event = db.query(Event).filter(Event.id == task.event_id).first()

        if event.user_id != user_id:
            raise AuthorizationError("You don't have permission to access this subtask")

        return subtask

    @staticmethod
    def update_subtask(
        db: Session,
        subtask_id: str,
        user_id: str,
        subtask_data: SubtaskUpdate,
    ) -> Subtask:
        """
        Update a subtask.

        Args:
            db: Database session
            subtask_id: Subtask ID
            user_id: User ID (for ownership verification)
            subtask_data: Subtask update data

        Returns:
            Updated Subtask object

        Raises:
            NotFoundError: If subtask not found
            AuthorizationError: If user doesn't own the event
        """
        subtask = TaskService.get_subtask_by_id(db, subtask_id, user_id)

        # Update only provided fields
        update_data = subtask_data.model_dump(exclude_unset=True)
        for field, value in update_data.items():
            setattr(subtask, field, value)

        subtask.updated_at = datetime.utcnow()
        db.commit()
        db.refresh(subtask)
        return subtask
